# Generated by Django 6.0.3 on 2026-03-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('prestation', models.CharField(choices=[('WEB', 'Application Web'), ('MOBILE', 'Application Mobile'), ('VITRINE', 'Site Vitrine'), ('CONSEIL', 'Audit & Consulting')], max_length=50)),
                ('description', models.TextField()),
                ('budget', models.CharField(max_length=50)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
