# Generated by Django 6.0.3 on 2026-09-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categorie', models.CharField(max_length=100, verbose_name='Catégorie (ex: E-commerce, Vitrine, Automatisation)')),
                ('description', models.TextField(verbose_name='Description du projet')),
                ('image', models.ImageField(upload_to='realisations/', verbose_name='Visuel du projet')),
                ('url_site', models.URLField(blank=True, null=True, verbose_name='Lien vers le projet')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de réalisation')),
                ('publie', models.BooleanField(default=True, verbose_name='Publié sur le site')),
            ],
        ),
    ]
